### ISSUE TITLE
Cloud: Gestionar el deploy en AWS

### ISSUE THREAD

**Issue by juan-nisimura** [leobz/organize-matches#90]
# Update 01/10/2022

## Aclaraciones

**Conexión desde el browser**: https://partidos.com.ar/ 

## Tasks

- [x] Creación de instancia Cloud (Ec2)
- [x]  Obtener Dominio
- [x]  Obtener DNS (CloudFlare)
- [x]  Obtener Certificado TSL (CertBot/ Let's Encrypt)
- [x]  Configurar Proxy Server con TSL / HTTPS (Nginx)
- [x]  Automatizar descarga/subida de imagenes de Regitsry (DockerHub) + docker-compose de producción en Makefile
- [x]  Actualizar CORS con nuevo dominio
- [x]  Contratar IP Estática o Elástica al momento de realizar Demo Final
- [x]  Invocar a Registry compartido + Externalizacion de enviroments variables
- [x]  Incluir diagrama de arquitectura actualizado y actualizar README.md con instrucciones

**Comment by leobz** [comment]
Comandos para instalar GIT+ Docker + Docker Compose en EC 2:
- https://gist.github.com/npearce/6f3c7826c7499587f00957fee62f8ee9

**Comment by leobz** [comment]
Prerequisitos:
- Tener images subidas a un registro publico, o privado

Cambios  necesarios relevados:
- Instalar GIT + DOCKER + DOCKER COMPOSE
- Logearse a registry docker en caso de que sea privado
- docker-compose -f docker-compose.yml -f production.yml up -d

Cambios necesarios para deploy basico 25/10 13 hs

![image](https://user-images.githubusercontent.com/43507646/197823494-2f43ff77-090c-49d4-b96c-fe28c02955bb.png)

**Comment by leobz** [comment]
## Bugs

**No se puede acceder a recursos privilegiados del backend  -> Unauthorized.

Si se refresca la pagina, el NavBar solo muestra recursos publicos**

![image](https://user-images.githubusercontent.com/43507646/197824243-d62bfd84-6389-4432-a90d-4a70c8d7a073.png)

Logs BE:

![image](https://user-images.githubusercontent.com/43507646/197824531-ecf743ed-e51a-4b4d-b424-3ecc09943fde.png)


**Causa:**

Cookie en el navegador no se setea:
![image](https://user-images.githubusercontent.com/43507646/197825743-22fbaa2e-317d-4a24-b060-f46ba9fc4ce4.png)

Tampoco se setea el localStorage:
![image](https://user-images.githubusercontent.com/43507646/197825966-c881f7f4-08f2-4a5a-9ffc-b525cf4e9e45.png)

**Comment by leobz** [comment]
Info relacionada al no seteo de cookie -> https://stackoverflow.com/questions/50300127/why-isnt-my-set-cookie-response-header-getting-translated-into-an-actual-cook
